### ISSUE TITLE
Docs for docker not quite alright

### ISSUE THREAD

**Issue by joaociocca** [actualbudget/actual-server#169]
So, I'm not shy from using command-line, but I'd love to see that easy one button setup thing.

For now, the path that most appealed to me was [using docker-compose](https://actualbudget.github.io/docs/Installing/Docker#launch-container-using-docker-compose), but that gave me an error:

```console
$ docker-compose --env-file .env up -d
Creating network "actual-server_default" with the default driver
Building actual_server
Sending build context to Docker daemon  4.608kB
Step 1/15 : FROM alpine:3.17 as base
3.17: Pulling from library/alpine
63b65145d645: Pull complete
Digest: sha256:ff6bdca1701f3a8a67e328815ff2346b0e4067d32ec36b7992c1fdc001dc8517
Status: Downloaded newer image for alpine:3.17
(...)
Removing intermediate container 716829f59e2d
 ---> 7aad3eb6c1f8
Step 4/15 : ADD .yarn ./.yarn
ADD failed: file not found in build context or excluded by .dockerignore: stat .yarn: file does not exist
ERROR: Service 'actual_server' failed to build : Build failed
```

So I thought, then, I'd get back to the README.md and follow the ["pure" Docker path](https://github.com/actualbudget/actual-server#running-via-docker). But that gave me a different error:

![image](https://user-images.githubusercontent.com/6473725/227073509-f70bfbc1-3900-4b84-b788-ea89e54d0667.png)

With a link to [this help page](https://actualbudget.github.io/docs/Troubleshooting/SharedArrayBuffer/). I thought "ok, I'm using the docker version, that should be easy..." specially since there's a link there called ["Activating HTTPS"](https://actualbudget.github.io/docs/Installing/HTTPS/).

Nope, no docker guidance for activating HTTPS (I have a small old PC I put Ubuntu server on and use for storage and small stuff, which is why I'm not running on localhost).

Now, I'm not that docker-savvy, I imagine there must be a way I can generate the self-signed certificates and map/volume them into Docker, but I have absolutely no idea on how to do that and would really appreciate some help.

**Comment by j-f1** [comment]
Hi!

- Here’s an updated `docker-compose.yml` file that unfortunately hasn’t been merged yet but does have the correct setup for pulling down the prebuilt container and mounting in a volume for data: https://github.com/actualbudget/actual-server/blob/jed/update-docker-compose/docker-compose.yml
- The docs in activating HTTPS should work for Docker too. Specifically, you should be able to generate the `.key` and `.crt` files using the methods suggested in the doc page. Then, put those files in the Actual data directory. Then you can set up either a config.json or the environment variables to point to those files. (Now that I write this up, I agree that there are some steps in there that should be added to the docs)

**Comment by joaociocca** [comment]
nice! Thank you very much, @j-f1 <3

Generated and put the selfhosted keys on `server-data`:

![image](https://user-images.githubusercontent.com/6473725/227101266-f2c0d5d8-510d-4884-bf9c-04c147ea7216.png)

Modified the `docker-compose.yml`:

![image](https://user-images.githubusercontent.com/6473725/227101306-52f90b68-69d5-41c8-bc05-73480f163f82.png)

```yml
version: "3"
services:
  actual_server:
    container_name: actual_server
    #build:
    #  context: ./
    #  dockerfile: Dockerfile
    image: jlongster/actual-server:latest-alpine
    ports:
      - "5006:5006"
    environment:
      - ACTUAL_SERVER_FILES=/data/server-files
      - ACTUAL_USER_FILES=/data/user-files
      - ACTUAL_HTTPS_KEY=/data/selfhost.key
      - ACTUAL_HTTPS_CERT=/data/selfhost.crt
    volumes:
      - ./server-data:/data
    restart: unless-stopped
```

One bad thing I noticed is that I can't create/link `user-files` directory.  If I do that, `docker-compose up` will exit in error:

![image](https://user-images.githubusercontent.com/6473725/227101405-b9879b06-a094-43ff-9750-1ae5c24d46db.png)

```console
$ sudo docker-compose --env-file .env up
Creating actual_server ... done
Attaching to actual_server
actual_server    | Error starting app: Error: EEXIST: file already exists, mkdir '/data/user-files'
actual_server    |     at Object.mkdirSync (node:fs:1395:3)
actual_server    |     at run (file:///app/src/app.js:56:8)
actual_server    |     at file:///app/app.js:3:1
actual_server    |     at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
actual_server    |   errno: -17,
actual_server    |   syscall: 'mkdir',
actual_server    |   code: 'EEXIST',
actual_server    |   path: '/data/user-files'
actual_server    | }
```

But, other than that little hiccup, it's up and running <3

![image](https://user-images.githubusercontent.com/6473725/227101653-383bc4f1-b32a-4a8a-a62f-1134ebb2f5bf.png)
