### ISSUE TITLE
Actual requires access to SharedArrayBuffer in order to function

### ISSUE THREAD

**Issue by tamis-laan** [actualbudget/actual-server#202]
Trying out actual for the first time using the example docker compose:
``` yaml
version: '3'

services:
  actual:
    image: actualbudget/actual-server:latest
    ports:
      - '3006:5006'
    volumes:
      - actual:/data
    restart: unless-stopped

volumes:
  actual:
    name: host-actual
```
Results in the following error message:
![screenshot](https://user-images.githubusercontent.com/3178666/236616218-0d27d558-5feb-4ac8-9cb2-29d5a65179bf.png)
The help page isn't very clear https://actualbudget.github.io/docs/Troubleshooting/SharedArrayBuffer/ 
I want to use actual over my local network, I'm not interested in exposing it to the internet. Thus I don't want to run https.
