### ISSUE TITLE
[Bug]: 23.12.0 rootless migrate permission error

### ISSUE THREAD

**Issue by brightdroid** [actualbudget/actual-server#288]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

After Upgrading to 23.12.0 the following permission error appears when running rootless (as before).

I am running actual in k3s with this pod securityContext:
```
  fsGroup: 64087
  runAsGroup: 64087
  runAsNonRoot: true
  runAsUser: 64087
  seccompProfile:
    type: RuntimeDefault
```
and container securityContext:
```
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsGroup: 64087
  runAsNonRoot: true
  runAsUser: 64087
```

I think the problem is the app tries to create a `.migrate` file in `/app` not in `/data`.

### What error did you receive?

```
Checking if there are any migrations to run for direction "up"...
file:///app/src/migrations.js:21
            throw err;
            ^

[Error: EACCES: permission denied, open '.migrate'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '.migrate'
}

Node.js v18.19.0

```

### Where are you hosting Actual?

Other

### What browsers are you seeing the problem on?

Chrome

### Operating System

Linux
