### ISSUE TITLE
[Bug]: Port 5006 is forced within docker

### ISSUE THREAD

**Issue by hrv231** [actualbudget/actual-server#313]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Hello,

If I give my Actual docker its own IP address,  the docker forces me to use port 5006, instead of 443 or 80.

Example:
```
services:
  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    ports:
      - '443:5006'
    environment:
      - ACTUAL_HTTPS_KEY=/data/selfhost.key
      - ACTUAL_HTTPS_CERT=/data/selfhost.crt
    volumes:
      - ./actual-data:/data
    restart: unless-stopped
    networks:
      my-network:
        ipv4_address: 10.10.10.10

networks:
  my-network:
    external: true
    name: my-network
```

### What error did you receive?

No error, but I think we should edit the Dockerbuild to not force port 5006, or allow an environment variable for when you are not using "bridge" network within docker.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Linux
