### ISSUE TITLE
Upgrading to version 22.10.25 not working in Docker

### ISSUE THREAD

**Issue by Marcus-Schubert** [actualbudget/actual-server#88]
Hey there,

I just tried to update to the latest version `22.10.25` of actual budget using docker Portainer. Download works fine, but after that the container stays in the state `created`. When trying to start the service manually I got an **HTTP error 400**.

Are there any breaking changes that would cause such a behavior?

I use the following docker compose

```
version: "3"
services:
  actual_server:
    image: jlongster/actual-server:latest
    container_name: actual_server
    ports:
      - "5006:5006"
    volumes:
      - /local_data:/data/
    restart: unless-stopped
```
