### ISSUE TITLE
Error: file does not exist: /data/user-files/file-***.blob

### ISSUE THREAD

**Issue by tensor5g** [actualbudget/actual-server#97]
After upgrading to 22.12.9 I get the above error after signing in from a new browser. I am using docker with the following compose:

```
version: "3"
services:
  budge:
    image: ***/actual-server:latest
    container_name: actual-budget
    volumes:
      - data:/data
    restart: unless-stopped


volumes:
  data:
```

Checking the filesystem, I don't see the blob file, but I do see the a directory of the same name. If I go back to the previous version (22.10.25 I think), it works fine. If I sync the client after updating, I get the same error after signing out.
